### PR TITLE
Add a new subcommand `hub pull-request info`

### PR DESCRIPTION
**Pull request by pcorpet**
I had to update the vendored octokit. I strongly recommend reviewing each commit separately as one is just about updating and the other one about adding the new feature.

[Review on Reviewable](https://reviewable.io/reviews/pcorpet/hub/1)

### CODE REVIEW

**Comment by pcorpet** [comment]
SGTM

**Comment by pcorpet** [comment]
A very very long comment on several
lines

**Comment by florianjourda** [comment]
lgtm!
Nice to see some Go for the first time :)

**Comment by florianjourda** [comment]
Reviewed 75 of 75 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/pcorpet/hub/1)_

**Pull request closed without merging**
